export const words = [
	{ word: 'Aras', translation: 'Олень' },
	{ word: 'Garaf', translation: 'Волк' },
	{ word: 'Gwilwileth', translation: 'Бабочка' },
	{ word: 'Laboth', translation: 'Заяц' },
	{ word: 'Brog', translation: 'Медведь' },
	{ word: 'Aew', translation: 'Птица' },
	{ word: 'Ithil', translation: 'Луна' },
	{ word: 'Orod', translation: 'Гора' },
	{ word: 'Ungol', translation: 'Паук' },
	{ word: 'Dûr', translation: 'Тёмный' },
	{ word: 'Ylf', translation: 'Сосуд («для питья»)' },
	{ word: 'Thalion', translation: 'Герой' },
	{ word: 'Draug', translation: 'Варг, волк' },
	{ word: 'Tiriel', translation: 'Смотритель' },
	{ word: 'Aer', translation: 'Море' },
	{ word: 'Lavan', translation: 'Зверь' },
	{ word: 'Lobor', translation: 'Лошадь' },
	{ word: 'Roch', translation: 'Лошадь, быстрая лошадь для езды' },
	{ word: 'Hû', translation: 'Собака' },
	{ word: 'Rŷn', translation: 'Охотничья собака, гончая' },
	{ word: 'Fileg', translation: 'Маленькая птица, “птичка”' },
	{ word: 'Lim', translation: 'Рыба' },
	{ word: 'Raw', translation: 'Лев' },
	{ word: 'Graw', translation: 'Медведь' },
	{ word: 'Rusc', translation: 'Лиса' },
	{ word: 'Annabon', translation: 'Слон' },
	{ word: 'Fara-', translation: 'Охотиться' },
	{ word: 'Lhûg', translation: 'Змея, червь' },
	{ word: 'Alph ', translation: 'Лебедь' },
	{ word: 'Cabor', translation: 'Лягушка' },
	{ word: 'Edhellen', translation: 'Синдарин, эльфийский язык' },
	{ word: 'Edhel (Edhil) ', translation: 'Эльф (Эльфы)' },
	{ word: 'Elleth', translation: 'Эльфийка' },
	{ word: 'Adan (Edain)', translation: 'Человек (Люди)' },
	{ word: 'Naug (Noeg)', translation: 'Гном (Гномы)' },
	{ word: 'Perian (Periain)', translation: 'Хоббит (Хоббиты)' },
	{ word: 'Imladris', translation: 'Ривенделл' },
	{ word: 'Lothlorien', translation: 'Лотлориен' },
	{ word: 'Ardh', translation: 'Земля (планета), страна (государство)' },
	{ word: 'Ma', translation: 'Да' },
	{ word: 'Uin', translation: 'Нет' },
	{ word: 'Eneth', translation: 'Имя' },
	{ word: 'Mellon (Mellyn)', translation: 'Друг (Друзья)' },
	{ word: 'Ped', translation: 'Говорить' },
	{ word: 'Can', translation: 'Кричать, звать' },
	{ word: 'Tir', translation: 'Смотреть, наблюдать' },
	{ word: 'Cen', translation: 'Видеть' },
	{ word: 'Nor', translation: 'Бежать, ехать верхом, скакать' },
	{ word: 'Cab', translation: 'Прыгать' },
	{ word: 'Linna', translation: 'Петь' },
	{ word: 'Minna', translation: 'Входить' },
	{ word: 'Aníra', translation: 'Желать, жаждать' },
	{ word: 'Dortha', translation: 'Жить' },
	{ word: 'Dartha', translation: 'Ждать' },
	{ word: 'Pada', translation: 'Идти' },
	{ word: 'Lasta', translation: 'Слышать' },
	{ word: 'Losta', translation: 'Спать' },
	{ word: 'Caradhras', translation: 'Карадрас (название гор)' },
	{ word: 'Lim', translation: 'Быстро, скоро' },
	{ word: 'Gar', translation: 'Иметь' },
	{ word: 'Tol', translation: 'Идти, приходить' },
	{ word: 'Revia', translation: 'Странствовать' },
	{ word: 'Teitha', translation: 'Писать' },
	{ word: 'Parf', translation: 'Книга' },
	{ word: 'Maetha', translation: 'Сражаться' },
	{ word: 'Gwanna', translation: 'Умирать' },
	{ word: 'Anor', translation: 'Солнце' },
	{ word: 'Mi', translation: 'В' },
	{ word: 'Na', translation: 'К, в' },
	{ word: 'Maer', translation: 'Хороший' }
];
