export const words = [
	{ word: 'Aras', translation: 'Олень' },
	{ word: 'Garaf', translation: 'Волк' },
	{ word: 'Gwilwileth', translation: 'Бабочка' },
	{ word: 'Laboth', translation: 'Заяц' },
	{ word: 'Brog', translation: 'Медведь' },
	{ word: 'Aew', translation: 'Птица' },
	{ word: 'Ithil', translation: 'Луна' },
	{ word: 'Orod', translation: 'Гора' },
	{ word: 'Ungol', translation: 'Паук' },
	{ word: 'Dûr', translation: 'Тёмный' },
	{ word: 'Ylf', translation: 'Сосуд («для питья»)' },
	{ word: 'Thalion', translation: 'Герой' },
	{ word: 'Draug', translation: 'Варг, волк' },
	{ word: 'Tiriel', translation: 'Смотритель' },
	{ word: 'Aer', translation: 'Море' },
	{ word: 'Lavan', translation: 'Зверь' },
	{ word: 'Lobor', translation: 'Лошадь' },
	{ word: 'Roch', translation: 'Лошадь, быстрая лошадь для езды' },
	{ word: 'Hû', translation: 'Собака' },
	{ word: 'Rŷn', translation: 'Охотничья собака, гончая' },
	{ word: 'Fileg', translation: 'Маленькая птица, “птичка”' },
	{ word: 'Lim', translation: 'Рыба' },
	{ word: 'Raw', translation: 'Лев' },
	{ word: 'Graw', translation: 'Медведь' },
	{ word: 'Rusc', translation: 'Лиса' },
	{ word: 'Annabon', translation: 'Слон' },
	{ word: 'Fara-', translation: 'Охотиться' },
	{ word: 'Lhûg', translation: 'Змея, червь' },
	{ word: 'Alph ', translation: 'Лебедь' },
	{ word: 'Cabor', translation: 'Лягушка' },
	{ word: 'Edhellen', translation: 'Синдарин, эльфийский язык' },
	{ word: 'Edhel (Edhil) ', translation: 'Эльф (Эльфы)' },
	{ word: 'Elleth', translation: 'Эльфийка' },
	{ word: 'Adan (Edain)', translation: 'Человек (Люди)' },
	{ word: 'Naug (Noeg)', translation: 'Гном (Гномы)' },
	{ word: 'Perian (Periain)', translation: 'Хоббит (Хоббиты)' },
	{ word: 'Imladris', translation: 'Ривенделл' },
	{ word: 'Lothlorien', translation: 'Лотлориен' },
	{ word: 'Ardh', translation: 'Земля (планета), страна (государство)' },
	{ word: 'Ma', translation: 'Да' },
	{ word: 'Uin', translation: 'Нет' },
	{ word: 'Eneth', translation: 'Имя' },
	{ word: 'Mellon (Mellyn)', translation: 'Друг (Друзья)' },
	{ word: 'Ped', translation: 'Говорить' },
	{ word: 'Can', translation: 'Кричать, звать' },
	{ word: 'Tir', translation: 'Смотреть, наблюдать' },
	{ word: 'Cen', translation: 'Видеть' },
	{ word: 'Nor', translation: 'Бежать, ехать верхом, скакать' },
	{ word: 'Cab', translation: 'Прыгать' },
	{ word: 'Linna', translation: 'Петь' },
	{ word: 'Minna', translation: 'Входить' },
	{ word: 'Aníra', translation: 'Желать, жаждать' },
	{ word: 'Dortha', translation: 'Жить' },
	{ word: 'Dartha', translation: 'Ждать' },
	{ word: 'Pada', translation: 'Идти' },
	{ word: 'Lasta', translation: 'Слышать' },
	{ word: 'Losta', translation: 'Спать' },
	{ word: 'Caradhras', translation: 'Карадрас (название гор)' },
	{ word: 'Lim', translation: 'Быстро, скоро' },
	{ word: 'Gar', translation: 'Иметь' },
	{ word: 'Tol', translation: 'Идти, приходить' },
	{ word: 'Revia', translation: 'Странствовать' },
	{ word: 'Teitha', translation: 'Писать' },
	{ word: 'Parf', translation: 'Книга' },
	{ word: 'Maetha', translation: 'Сражаться' },
	{ word: 'Gwanna', translation: 'Умирать' },
	{ word: 'Anor', translation: 'Солнце' },
	{ word: 'Mi', translation: 'В' },
	{ word: 'Na', translation: 'К, в' },
	{ word: 'Maer', translation: 'Хороший' },
	{ word: 'Mallen', translation: 'Золотой' },
	{ word: 'Celeb', translation: 'Серебряный' },
	{ word: 'Rustui', translation: 'Медный' },
	{ word: 'Man', translation: 'Что' },
	{ word: 'Mel', translation: 'Любить' },
	{ word: 'Sen', translation: 'Это' },
	{ word: 'Thand', translation: 'Правда' },
	{ word: 'Dan', translation: 'Но' },
	{ word: 'Haered', translation: 'Даль, большое расстояние' },
	{ word: 'Ista', translation: 'Знать' },
	{ word: 'Milui', translation: 'Дружелюбный, добрый' },
	{ word: 'Bain', translation: 'Красивый' },
	{ word: 'Sael', translation: 'Мудрый' },
	{ word: 'Caras', translation: 'Поселение (чаще на деревьях)' },
	{ word: 'Galadh', translation: 'Дерево' },
	{ word: 'Lad', translation: 'Долина' },
	{ word: 'Calad', translation: 'Свет' },
	{ word: 'Amon', translation: 'Холм' },
	{ word: 'Ost', translation: 'Город' },
	{ word: 'Sîr', translation: 'Река, поток' },
	{ word: 'Gwilith', translation: 'Небо' },
	{ word: 'Lanthir', translation: 'Водопад' },
	{ word: 'Ithron', translation: 'Маг, волшебник' },
	{ word: 'Othronn', translation: 'Подземный город, крепость' },
	{ word: 'Gopad', translation: 'Идти с (кем-то)' },
	{ word: 'Caeleb', translation: 'Больной, заболевший, нездоровый' },
	{ word: 'Taur', translation: 'Лес' },
	{ word: 'Govad', translation: 'Встречать' },
	{ word: 'Arad', translation: 'День' },
	{ word: 'Tog', translation: 'Вести (кого-то), приносить' },
	{ word: 'Pol', translation: 'Мочь, быть способным' },
	{ word: 'Tulu', translation: 'Помогать, помощь' },
	{ word: 'Sí', translation: 'Здесь' },
	{ word: 'Ennas', translation: 'Там' },
	{ word: 'Men', translation: 'Нас, нами' },
	{ word: 'Dag', translation: 'Убивать' },
	{ word: 'Sain', translation: 'Их' },
	{ word: 'Gín', translation: 'Твой' },
	{ word: 'Fîr', translation: 'Умирать' },
	{ word: 'Nen (nîn)', translation: 'Вода (воды)' },
	{ word: 'A Elbereth', translation: 'А Элберет (Обращение к Варде – слава богу; о боже и т.д.)' },
	{ word: 'Hannon', translation: 'Благодарю' },
	{ word: 'Glassen', translation: 'Пожалуйста (ответ на спасибо)' },
	{ word: 'Caran', translation: 'Красный' },
	{ word: 'Carnin', translation: 'Алый' },
	{ word: 'Luin', translation: 'Синий' },
	{ word: 'Elu', translation: 'Голубой' },
	{ word: 'Malen', translation: 'Жёлтый' },
	{ word: 'Calen, Laeg (арх.)', translation: 'Зелёный, зелёный (арх.)' },
	{ word: 'Morn', translation: 'Чёрный' },
	{ word: 'Baran', translation: 'Тёмно-коричневый' },
	{ word: 'Rhosg', translation: 'Коричневый' },
	{ word: 'Faen, fain', translation: 'Белый' },
	{ word: 'Nimp', translation: 'Бледный' },
	{ word: 'Glos', translation: 'Белоснежный' },
	{ word: 'Mith', translation: 'Серый' },
	{ word: 'Cull', translation: 'Оранжевый' },
	{ word: 'Crinth', translation: 'Розовый' },
	{ word: 'Ling', translation: 'Фиолетовый' }
];
